# Generated by Django 2.2.16 on 2021-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
