# Generated by Django 2.2.16 on 2021-09-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210912_1737'),
        ('reviews', '0002_auto_20210912_1729'),
    ]

    operations = [
    ]
